version: "3.9"

services:
  dns:
  networks:
    testnet:
      ipv4_address: 172.30.0.10

dhcp:
  networks:
    testnet:
      ipv4_address: 172.30.0.2
    cap_add:
      - NET_ADMIN

  client:
    build: ./client
    container_name: client
    networks:
      testnet:
    cap_add:
      - NET_ADMIN

networks:
  testnet:
    external: true
